### ISSUE TITLE
Nodejs 12 deprecation warning

### ISSUE THREAD

**Issue by ghost** [cbuschka/setup-tfvm#10]
Moin!
Currently github issues a warning for actions that use Node.js 12 and below.
Looks like tfvm is using NodeJs 12.

Following warning:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: cbuschka/setup-tfvm@v1

**Comment by cbuschka** [comment]
Hey @tdymel, thanks for raising an issue. Sorry I was not aware of the deprecation of node 12. Interested in preparing a pull request? ;) Otherwise I will do the update.

**Comment by Geigerkind** [comment]
Probably better if you just update it, as I have no idea what updating node implies in the node environment. Never worked with this technology seriously ;)

**Comment by ghost** [comment]
Probably better if you just update it, as I have no idea what updating node implies in the node environment. Never worked with this technology seriously ;)

**Comment by cbuschka** [comment]
Moin @tdymel,
just have updated the node version. (It's the little thing that causes big problems.)

Currently v1 still points to the old version, also known as v1.0.0. I have added the updated version as v1.0.1, so you could reference it through setup-tfvm@v1.0.1 instead of setup-tfvm@v1.

Could you please verify if it works for you, too. I will do the same in my projects on tomorrow. If we both have verified I will move the v1 tag from v1.0.0 to point to v1.0.1. Ok?

Thanks in advance. Best Conni

**Comment by ghost** [comment]
Hey Conni,
thanks for updating it so quickly. 
I just updated it in our environment and everything still works without deprecation warnings :)

Thanks a lot!
Cheers!
Tom

**Comment by cbuschka** [comment]
Hey Tom,

I just have switched v1 to point to v1.0.1.

Thanks for the issue and feedback.

All the Best
Conni
